livraison_index:
    path:     /
    defaults: { _controller: "VenteBundle:Livraison:index" }
    methods:  GET

livraison_show:
    path:     /{id}/show
    defaults: { _controller: "VenteBundle:Livraison:show" }
    methods:  GET

livraison_new:
    path:     /new
    defaults: { _controller: "VenteBundle:Livraison:new" }
    methods:  [GET, POST]

livraison_edit:
    path:     /{id}/edit
    defaults: { _controller: "VenteBundle:Livraison:edit" }
    methods:  [GET, POST]

livraison_delete:
    path:     /{id}/delete
    defaults: { _controller: "VenteBundle:Livraison:delete" }
    methods:  DELETE
